feat: index nature juridique as keyword
etalab/annuaire-entreprises-search-infra pull request #113
Opened 2023-02-16 13:53 UTC by HAEKADI

related to https://github.com/etalab/annuaire-entreprises-search-api/issues/172
Change `nature_juridique_unite_legale` mapping to keyword in order to use a prefix query to filter on it.

2023-02-17 08:30 UTC, geoffreyaldebert approved these changes
Waw I did not see that we missed that before

2023-02-17 09:20 UTC, XavierJp approved these changes

2023-02-17 11:19 UTC, HAEKADI commented
This PR adds `est_service_public` to elasticsearch`s mapping and preprocesses its value based on ` nature_juridique_unite_legale`.

2023-02-17 13:14 UTC, XavierJp requested changes

2023-02-17 13:14 UTC, XavierJp commented on data_enrichment.py
> +    if nature_juridique_unite_legale and nature_juridique_unite_legale.startswith(
Ajouter la condition debut de siren = 1 ou 2

2023-02-17 15:33 UTC, HAEKADI commented on data_enrichment.py
> +    if nature_juridique_unite_legale and nature_juridique_unite_legale.startswith(
Done!

2023-02-20 08:51 UTC, XavierJp approved these changes

2023-02-20 08:51 UTC, XavierJp commented on data_enrichment.py
> +            ("3210", "3110", "4", "71", "72", "73", "74")
Nice de pouvoir passer un tuple dans `startswith` !

2023-02-20 08:59 UTC, merged