[Snapshot] Store the current index version on MinIO | Update the local siren-reader alias after each index
etalab/annuaire-entreprises-search-infra pull request #258
Opened 2024-01-29 16:09 UTC by MKCG

This PR introduces 3 changes :

1. The `siren-reader` alias is also locally updated after a successful indexing for compatibility with the dev instance
2. The new daily index version is stored on MinIO
3. A new DAG to restore the previous index version based on the previous index version stored on MinIO

2024-02-06 09:51 UTC, HAEKADI requested changes

2024-02-06 09:51 UTC, HAEKADI commented on workflows/data_pipelines/elasticsearch/task_functions/snapshot.py
> +def update_minio_current_index_version(**kwargs):
Add one liner for function purpose here if possible :)

2024-02-06 09:51 UTC, HAEKADI commented on helpers/minio_helpers.py
> +    def read_json_file(self, dest_path, dest_name):
If possible to use existing methods within the class and add helpers for temp file creation. that would be great !

2024-03-04 09:18 UTC, MKCG commented
Relates to https://github.com/etalab/annuaire-entreprises-search-infra/pull/258

2024-03-04 14:08 UTC, HAEKADI approved these changes
🚀

2024-03-04 14:19 UTC, merged